#!/bin/bash
#изменить recent.jpg на название текущего файла, new.jpg на название нового файла
mv Downloads/new.jpg shell-theme/theme/
cd shell-theme/theme
nvim gnome-shell-theme.gresource.xml
sed "s/recent/new/g" gnome-shell-theme.gresource.xml > gnome-shell-theme.gresource.xml.new #change recent.jpg to new.jpg
mv gnome-shell-theme.gresource.xml.new gnome-shell-theme.gresource.xml
glib-compile-resources gnome-shell-theme.gresource.xml
nvim gnome-shell.css
sed "s/recent/new/g" gnome-shell.css > gnome-shell.css.new #change recent.jpg to new.jpg
mv gnome-shell.css.new gnome-shell.css
cp gnome-shell-theme.gresource /usr/share/gnome-shell 
